# Generated by Django 4.0.5 on 2022-07-24 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/imgs/profiles/profile_default.png', null=True, upload_to='static/imgs/profiles/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_body', models.TextField(max_length=2000)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('is_it_answer', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comment')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
