# Generated by Django 4.0.5 on 2022-07-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_comment_is_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_to_comment', to='users.comment'),
        ),
    ]
