# Generated by Django 4.0.5 on 2022-08-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_answer_answer_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='comment',
        ),
        migrations.AddField(
            model_name='activity',
            name='to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='activities',
            field=models.ManyToManyField(blank=True, to='users.activity'),
        ),
    ]
