# Generated by Django 4.0.4 on 2022-07-03 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWebsite',
            fields=[
                ('website_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsWebsite',
            fields=[
                ('website_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('synopsis', models.CharField(blank=True, max_length=2000, null=True)),
                ('link_main', models.CharField(max_length=2000)),
                ('image_link_main', models.CharField(blank=True, max_length=2000, null=True)),
                ('publish_time', models.CharField(blank=True, max_length=200, null=True)),
                ('was_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image_link_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.imagewebsite')),
                ('link_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newswebsite')),
            ],
        ),
    ]
