# Generated by Django 4.0.5 on 2022-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_path',
            field=models.ImageField(blank=True, default='article_default.png', null=True, upload_to='imgs/'),
        ),
    ]
