# Generated by Django 4.0.5 on 2022-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_path',
            field=models.CharField(blank=True, default='imgs/article_default.png', max_length=2000, null=True),
        ),
    ]
