# Generated by Django 4.0.5 on 2022-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('article_link', models.CharField(blank=True, max_length=500, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('image_link', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newswebsite',
            name='get_news_link',
            field=models.CharField(default='https://www.pcgamer.com/news/', max_length=2000),
        ),
    ]
