# Generated by Django 4.0.5 on 2022-07-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_searchables_newswebsite_get_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchables',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newswebsite'),
        ),
        migrations.AlterField(
            model_name='newswebsite',
            name='get_news_link',
            field=models.CharField(max_length=2000),
        ),
    ]
