# Generated by Django 4.0.5 on 2022-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newswebsite_get_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewebsite',
            name='num_to_chop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
