# Generated by Django 4.0.5 on 2022-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_imagewebsite_num_to_chop'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='raw_publish_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
